name: CI

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Generate application key
      run: php artisan key:generate

    - name: Configure database
      run: |
        php artisan config:clear
        php artisan config:cache
        touch database/database.sqlite

    - name: Run migrations
      run: |
        php artisan migrate --force
        php artisan db:seed
  
    - name: Run tests
      run: vendor/bin/phpunit
